FROM chronongraf
RUN apt-get update
RUN apt-get install python-pip3 -y
RUN docker images -y
RUN docker pull chronograf
RUN docker images -y
RUN docker container ls -y
RUN docker run chronograf
RUN docker container ls -y


  



