FROM influxdb
RUN apt-get update
RUN apt-get install python-pip3 -y
RUN docker images -y
RUN docker pull influxdb
RUN docker images -y
RUN docker container ls -y
RUN docker run influxdb
RUN docker container ls -y